# Generated by Django 5.0.2 on 2024-03-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'shoe colors',
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'shoe sizes',
            },
        ),
        migrations.CreateModel(
            name='sub_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_path', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'small images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Jordan', 'Jordan'), ('Nike', 'Nike'), ('Puma', 'Puma'), ('Adidas', 'Adidas'), ('New Balance', 'New Balance'), ('Reebok', 'Reebok'), ('Vans', 'Vans')], max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categories', models.CharField(choices=[('trending', 'trending'), ('outdoor', 'outdoor'), ('discounted', 'discounted'), ('new', 'new')], max_length=20)),
                ('discount', models.BooleanField(default=False)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('colors', models.ManyToManyField(to='shoe_items.shoecolor')),
                ('sizes', models.ManyToManyField(to='shoe_items.shoesize')),
                ('small_images', models.ManyToManyField(blank=True, to='shoe_items.sub_image')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
