# Generated by Django 5.0.2 on 2024-03-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_items', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='sub_image',
            old_name='img_path',
            new_name='image_path',
        ),
    ]
