# Generated by Django 5.0.2 on 2024-03-05 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_items', '0004_rename_brand_product_brands_favorite_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.CharField(choices=[('jordan', 'jordan'), ('nike', 'nike'), ('puma', 'puma'), ('adidas', 'adidas'), ('new_balance', 'new_balance'), ('reebok', 'reebok'), ('vans', 'vans')], max_length=20),
        ),
    ]
